[workspace]
members = [
    "node",
    "pallets/template",
    "pallets/paymentchannels",
    "pallets/streampayments",
    "pallets/tokens",
    "pallets/utilities",
    "pallets/traits",
    "pallets/escrow",
    "runtime",
]
resolver = "2"
[profile.release]
panic = "unwind"
